- hosts: all
  tasks:
  - package:
      name: "httpd"
      state: present

  - copy:
      src: "/root/index.html"
      dest: "/var/www/html/new.html"

  - service:
      name: "httpd"
      state: restarted
